//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCD_Stadium_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadium
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StadiumType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
